import Mathlib
import Lean

open Lean Elab Tactic Meta

namespace WZProver
namespace Tactic

/-!
  `auto_side` tactic — side conditions generated by the WZ prover.

  Pattern coverage (645 lemmas in WZ_Sketch):
    1. ne_zero_cast_linarith  (一半): linear expressions over ℕ-cast-to-ℝ that are ≠ 0
    2. binom_ne_zero          (20%): `(n.choose k) ≠ 0` and `¬ n.choose k = 0`
    3. eq_recurrence          (10%): power equalities of the form `2^a = 2^b * c`
    4. ne_zero_pow            (5 %): `(expr)^k ≠ 0` from positivity or pow_ne_zero
    5. trivial_eq             (10%): `a = a * 1`, `(-1)^n = (-1)^n * 1`.
-/

/-- Try a tactic and return true only if it **closes all goals**.
    If it fails or leaves goals open, restore state and return false. -/
private def tryClosingTactic (tac : TSyntax `tactic) : TacticM Bool := do
  let s ← saveState
  try
    evalTactic tac
    if (← getGoals).isEmpty then
      return true
    else
      restoreState s
      return false
  catch _ =>
    restoreState s
    return false

/-- Run an array of tactics, returning true if any one closes all goals. -/
private def tryTacticList (tactics : Array (TSyntax `tactic)) (errMsg : String) : TacticM Unit := do
  if (← getGoals).isEmpty then return
  for tac in tactics do
    if ← tryClosingTactic tac then return
  throwError errMsg


-- ══════════════════════════════════════════════════════════════
-- ne_zero_by_cast: bridge ℕ hypotheses to ℝ, then linarith
-- ══════════════════════════════════════════════════════════════

/-- Prove `(expr : ℝ) ≠ 0` where expr involves ℕ-casts, by intro-ing = 0,
    casting all ℕ order hypotheses to ℝ, then linarith. -/
syntax (name := neZeroByCast) "ne_zero_by_cast" : tactic

@[tactic neZeroByCast]
def evalNeZeroByCast : Tactic := fun _ => do
  evalTactic (← `(tactic| intro _h_ne_zero_assum_))
  -- Cast all ℕ order hypotheses to ℝ by trying each one
  withMainContext do
    let ctx ← getLCtx
    let mut castIdx : Nat := 0
    for decl in ctx do
      if decl.isAuxDecl || decl.isImplementationDetail then continue
      let nm := decl.userName
      if nm.isAnonymous then continue
      let hypRef := mkIdent nm
      castIdx := castIdx + 1
      let freshNm := mkIdent (Name.mkSimple s!"_hcast{castIdx}")
      -- Try casting the hypothesis (or its parts) as a ℝ inequality
      for expr in #[
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) < Nat.cast _ := Nat.cast_lt.mpr $hypRef),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) ≤ Nat.cast _ := Nat.cast_le.mpr $hypRef),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) < Nat.cast _ := Nat.cast_lt.mpr ($hypRef).1),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) ≤ Nat.cast _ := Nat.cast_le.mpr ($hypRef).1),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) < Nat.cast _ := Nat.cast_lt.mpr ($hypRef).2),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) ≤ Nat.cast _ := Nat.cast_le.mpr ($hypRef).2),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) < Nat.cast _ := Nat.cast_lt.mpr ($hypRef).2.1),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) ≤ Nat.cast _ := Nat.cast_le.mpr ($hypRef).2.1),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) < Nat.cast _ := Nat.cast_lt.mpr ($hypRef).2.2),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) ≤ Nat.cast _ := Nat.cast_le.mpr ($hypRef).2.2),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) < Nat.cast _ := Nat.cast_lt.mpr ($hypRef).2.2.1),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) ≤ Nat.cast _ := Nat.cast_le.mpr ($hypRef).2.2.1),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) < Nat.cast _ := Nat.cast_lt.mpr ($hypRef).2.2.2),
        ← `(tactic| have $freshNm : (Nat.cast _ : ℝ) ≤ Nat.cast _ := Nat.cast_le.mpr ($hypRef).2.2.2)
      ] do
        try evalTactic expr catch _ => pure ()
  try evalTactic (← `(tactic| linarith))
  catch _ =>
  try evalTactic (← `(tactic| nlinarith [Nat.zero_le _]))
  catch _ =>
    throwError "ne_zero_by_cast: linarith/nlinarith failed after casting ℕ hypotheses to ℝ"


-- ══════════════════════════════════════════════════════════════
-- Pattern 1 & 4: nonzero goals  (≠ 0 or ¬ _ = 0)
-- ══════════════════════════════════════════════════════════════

syntax (name := autoNeZero) "auto_ne_zero" : tactic

@[tactic autoNeZero]
def evalAutoNeZero : Tactic := fun _ => do
  let tactics : Array (TSyntax `tactic) := #[
    -- constants like (2 : ℝ) ≠ 0
    ← `(tactic| norm_num),
    -- positivity covers: `0 < e` then `e ≠ 0`; handles powers, casts, products
    ← `(tactic| positivity),
    -- ℕ cast: n ≥ 0, linear combo > 0 → ≠ 0
    ← `(tactic| (push_cast; intro h; have := Nat.zero_le _; linarith)),
    ← `(tactic| (intro h; push_cast at *; linarith)),
    -- cast + nlinarith for nonlinear combinations
    ← `(tactic| (intro h; have h1 := Nat.zero_le _; push_cast at *; nlinarith)),
    -- pow_ne_zero: if base ≠ 0 then base^n ≠ 0 (covers (-1)^n ≠ 0 too)
    ← `(tactic| (apply pow_ne_zero; norm_num)),
    ← `(tactic| (apply pow_ne_zero; positivity)),
    -- cast ne_zero via omega on ℕ side
    ← `(tactic| (intro h; norm_cast at h; omega)),
    -- choose ≠ 0: Nat.choose_pos
    ← `(tactic| (apply Nat.ne_of_gt; apply Nat.choose_pos; omega)),
    ← `(tactic| (apply Nat.pos_of_ne_zero; intro h; simp [h] at *; omega)),
    -- ¬ expr = 0 form: convert to ≠ and retry
    ← `(tactic| (simp only [ne_eq]; norm_num)),
    ← `(tactic| (simp only [ne_eq]; positivity)),
    -- cast nonzero: e.g. (↑(choose n k) : ℝ) ≠ 0
    ← `(tactic| (norm_cast; apply Nat.ne_of_gt; apply Nat.choose_pos; omega)),
    ← `(tactic| (norm_cast; omega)),
    -- squared expression ≠ 0: pow_ne_zero from base ≠ 0
    ← `(tactic| (apply pow_ne_zero; intro h; push_cast at *; linarith)),
    ← `(tactic| (apply pow_ne_zero; intro h; push_cast at *; nlinarith)),
    -- ══ NEW: ℕ→ℝ cast bridge (core fix) ══
    -- Cast ℕ hypotheses (n ≥ 1, n > x, etc.) to ℝ, then linarith
    ← `(tactic| ne_zero_by_cast),
    -- sub_eq_zero for simple cast differences: ↑a - ↑b = 0 → a = b → omega
    ← `(tactic| (intro h; rw [sub_eq_zero] at h; norm_cast at h; omega)),
    -- simp away ↑0 / sub_zero, then positivity or ne_zero_by_cast
    ← `(tactic| (simp only [Nat.cast_zero, sub_zero]; positivity)),
    ← `(tactic| (simp only [Nat.cast_zero, sub_zero]; ne_zero_by_cast)),
    -- push_neg + cast bridge
    ← `(tactic| (push_neg; ne_zero_by_cast)),
    -- General: reduce to ℕ via norm_cast then omega (handles ↑a - ↑b = c parity)
    ← `(tactic| (intro h; norm_cast at h; omega)),
    ← `(tactic| (intro h; norm_cast at h ⊢; omega)),
    -- ℤ-cast bridge: cast ℝ equality to ℤ then omega (handles ↑a - ↑b + c = 0 with ≠/≤/< context)
    ← `(tactic| (intro h; have _hZ_ : _ = (0 : ℤ) := by exact_mod_cast h; omega)),
    ← `(tactic| (intro h; push_cast at h; have _hZ_ : _ = (0 : ℤ) := by exact_mod_cast h; omega)),
    -- last resort: decide
    ← `(tactic| (push_neg; push_cast; linarith [Nat.zero_le _]))
  ]
  tryTacticList tactics
    "auto_ne_zero: could not discharge this nonzero goal automatically"


-- ══════════════════════════════════════════════════════════════
-- Pattern 2: binomial coefficient nonzero
-- ══════════════════════════════════════════════════════════════

syntax (name := autoBinomPos) "auto_binom_pos" : tactic

@[tactic autoBinomPos]
def evalAutoBinomPos : Tactic := fun _ => do
  let tactics : Array (TSyntax `tactic) := #[
    -- direct: choose_pos when k ≤ n provable by omega
    ← `(tactic| (apply Nat.choose_pos; omega)),
    -- negation form: ¬ n.choose k = 0
    ← `(tactic| (intro h; have := Nat.choose_pos (by omega : _ ≤ _); omega)),
    -- ne_of_gt form
    ← `(tactic| (apply Nat.ne_of_gt; apply Nat.choose_pos; omega)),
    -- squared choose, cast to ℝ
    ← `(tactic| (norm_cast; apply Nat.ne_of_gt; apply pow_pos; apply Nat.choose_pos; omega)),
    ← `(tactic| (norm_cast; apply pow_ne_zero; apply Nat.ne_of_gt; apply Nat.choose_pos; omega)),
    -- cast ℕ → ℝ nonzero via norm_cast + choose_pos
    ← `(tactic| (norm_cast; apply Nat.choose_pos; omega)),
    ← `(tactic| (have h := Nat.choose_pos (by omega : _ ≤ _); norm_cast; omega)),
    -- simp path
    ← `(tactic| (simp [Nat.choose_pos, *]; omega)),
    -- fallback to auto_ne_zero
    ← `(tactic| auto_ne_zero)
  ]
  tryTacticList tactics
    "auto_binom_pos: could not discharge this binomial nonzero goal automatically"


-- ══════════════════════════════════════════════════════════════
-- Pattern 3: power recurrence equalities
-- ══════════════════════════════════════════════════════════════

syntax (name := autoPowRec) "auto_pow_rec" : tactic

@[tactic autoPowRec]
def evalAutoPowRec : Tactic := fun _ => do
  let tactics : Array (TSyntax `tactic) := #[
    -- ring handles it directly (e.g. 2^(n+1) = 2^n * 2)
    ← `(tactic| ring),
    -- push_cast then ring
    ← `(tactic| (push_cast; ring)),
    -- pow_succ rewrite + ring
    ← `(tactic| (rw [pow_succ]; ring)),
    ← `(tactic| (rw [pow_add]; norm_num)),
    ← `(tactic| (rw [pow_add]; ring)),
    -- push_cast + pow_add + norm_num
    ← `(tactic| (push_cast [pow_add, pow_succ]; ring)),
    ← `(tactic| (push_cast [pow_add, pow_succ]; norm_num)),
    -- ring_nf normalises mixed nat/real exponents
    ← `(tactic| (ring_nf; norm_cast)),
    ← `(tactic| (ring_nf; push_cast; ring)),
    -- simp with ring lemmas then norm_num
    ← `(tactic| (simp [pow_add, pow_succ, pow_mul, mul_comm, mul_assoc]; ring_nf; norm_num)),
    ← `(tactic| (norm_cast; ring)),
    ← `(tactic| (push_cast; simp [pow_succ, pow_add, mul_comm]; ring)),
    -- ══ NEW: exponents with ℕ subtraction ══
    -- e.g. 2^(2*(n+1)-2) = 2^(2*n-2) * 4
    -- Strategy: rewrite LHS exponent = RHS exponent + k via omega, then pow_add + norm_num
    ← `(tactic| (
      conv_lhs => rw [show _ = _ + _ from by omega];
      rw [pow_add]; norm_num)),
    ← `(tactic| (
      conv_lhs => rw [show _ = _ + _ from by omega];
      rw [pow_add]; ring)),
    ← `(tactic| (
      conv_rhs => rw [show _ * _ = _ ^ (_ + _) from by rw [pow_add]; ring];
      congr 1; omega)),
    -- congr on base, omega on exponents
    ← `(tactic| (congr 1; omega)),
    ← `(tactic| (norm_cast; congr 1; omega)),
    -- ℕ subtraction in exponent: 2^(2*(n+1)-2) = 2^(2*n-2) * 4
    -- Key: find k s.t. RHS_exp + k = LHS_exp by omega, then use pow_add
    ← `(tactic| (rw [show _ = _ + 2 from by omega, pow_add]; norm_num)),
    ← `(tactic| (rw [show _ = _ + 1 from by omega, pow_add]; norm_num)),
    ← `(tactic| (rw [show _ = _ + 2 from by omega, pow_add]; ring)),
    ← `(tactic| (rw [show _ = _ + 1 from by omega, pow_add]; ring)),
    -- Rewrite RHS constant as power: 4 = 2^2, 2 = 2^1, then ← pow_add + congr
    ← `(tactic| (rw [show (4 : ℝ) = 2^2 by norm_num, ← pow_add]; congr 1; omega)),
    ← `(tactic| (rw [show (2 : ℝ) = 2^1 by norm_num, ← pow_add]; congr 1; omega)),
    ← `(tactic| (norm_cast; rw [show (4 : ℕ) = 2^2 by norm_num, ← pow_add]; congr 1; omega)),
    ← `(tactic| (norm_cast; rw [show (2 : ℕ) = 2^1 by norm_num, ← pow_add]; congr 1; omega))
  ]
  tryTacticList tactics
    "auto_pow_rec: could not discharge this power recurrence goal automatically"


-- ══════════════════════════════════════════════════════════════
-- Pattern 5: trivial equalities  (a = a * 1, a * 1 = a, etc.)
-- ══════════════════════════════════════════════════════════════

syntax (name := autoTrivialEq) "auto_trivial_eq" : tactic

@[tactic autoTrivialEq]
def evalAutoTrivialEq : Tactic := fun _ => do
  let tactics : Array (TSyntax `tactic) := #[
    ← `(tactic| ring),
    ← `(tactic| (simp [mul_one, one_mul])),
    ← `(tactic| (push_cast; ring)),
    ← `(tactic| (norm_cast; ring)),
    ← `(tactic| (simp [mul_one]; ring_nf))
  ]
  tryTacticList tactics
    "auto_trivial_eq: could not discharge this trivial equality automatically"


-- ══════════════════════════════════════════════════════════════
-- Master tactic: tries all patterns in order
-- ══════════════════════════════════════════════════════════════

syntax (name := autoSide) "auto_side" : tactic

@[tactic autoSide]
def evalAutoSide : Tactic := fun _ => do
  let tactics : Array (TSyntax `tactic) := #[
    -- cheapest first: pure arithmetic / ring
    ← `(tactic| norm_num),
    ← `(tactic| omega),
    ← `(tactic| ring),
    ← `(tactic| (push_cast; ring)),
    -- nonzero goals
    ← `(tactic| auto_ne_zero),
    -- binomial nonzero goals
    ← `(tactic| auto_binom_pos),
    -- power recurrence equalities
    ← `(tactic| auto_pow_rec),
    -- trivial multiplicative equalities
    ← `(tactic| auto_trivial_eq),
    -- broader automation as fallback
    ← `(tactic| positivity),
    ← `(tactic| (simp [*]; omega)),
    ← `(tactic| (push_cast; linarith [Nat.zero_le _])),
    ← `(tactic| (norm_cast; simp [Nat.choose_pos, *]; omega)),
    ← `(tactic| (simp only [ne_eq, not_false_eq_true]; positivity)),
    -- ℕ→ℝ cast bridge as top-level fallback
    ← `(tactic| ne_zero_by_cast),
    ← `(tactic| decide)
  ]
  tryTacticList tactics
    "auto_side: all patterns exhausted — this goal needs a manual or model-generated proof"

end Tactic
end WZProver
